# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hw7',
                'doc_host': 'https://jtrichWM.github.io',
                'git_url': 'https://github.com/jtrichWM/hw7',
                'lib_path': 'hw7'},
  'syms': {'hw7.core': {'hw7.core.foo': ('core.html#foo', 'hw7/core.py')}}}